# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
     # matrix:
      #  node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        # Artifact name
        name: my-artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}
        
  deployment:
    runs-on: ubuntu
    needs: [build]
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.7
      with:
        # Artifact name
        name: my-artifact
    
       
